import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Signika } from "next/font/google";
import "./globals.css";
import Navbar from "./sharedLayouts/Navbar";

const signika = Signika({ subsets: ["latin"] });

// Signika Negative

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={signika.className}>
        <Navbar/>
        <hr className="border-b-0 border-gray-500 " />
        {children}
        </body>
    </html>
  );
}
